# Generated by Django 4.2 on 2024-09-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=13)),
                ('location_text', models.CharField(max_length=255)),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('telegram', models.URLField()),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor', models.CharField(max_length=100)),
                ('CPU', models.CharField(max_length=100)),
                ('GPU', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'computer',
                'verbose_name_plural': 'computers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='courses/')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_duration_time', models.CharField(max_length=100)),
                ('theory_duration_time', models.CharField(max_length=100)),
                ('theory_text', models.TextField(verbose_name='practical_text')),
                ('practical_duration_time', models.CharField(max_length=100)),
                ('practical_text', models.TextField(verbose_name='practical_text')),
            ],
            options={
                'verbose_name': 'course plan',
                'verbose_name_plural': 'course plans',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='ModuleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=250, verbose_name='practical_text')),
            ],
            options={
                'verbose_name': 'module lesson',
                'verbose_name_plural': 'module lessons',
            },
        ),
        migrations.CreateModel(
            name='OurProgramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=1)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Our program info',
                'verbose_name_plural': 'Our program infos',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='partners/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name': 'place of work',
                'verbose_name_plural': 'places of work',
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Student Feedback',
                'verbose_name_plural': 'Student Feedback',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='teams/')),
                ('job', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'WhyUs',
                'verbose_name_plural': 'WhyUs',
            },
        ),
        migrations.CreateModel(
            name='UserContactApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.course')),
            ],
            options={
                'verbose_name': 'user contact application',
                'verbose_name_plural': 'user contact applications',
            },
        ),
        migrations.CreateModel(
            name='OurProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='programs/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('program_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ourprograminfo')),
            ],
            options={
                'verbose_name': 'our program',
                'verbose_name_plural': 'our programs',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=250, verbose_name='practical_text')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.modulelesson')),
            ],
            options={
                'verbose_name': 'course module',
                'verbose_name_plural': 'course modules',
            },
        ),
        migrations.CreateModel(
            name='CourseMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='course_mentor/%Y/%m/%d')),
                ('experience', models.TextField(verbose_name='experience')),
                ('projects_involved', models.TextField()),
                ('disciple', models.TextField()),
                ('place_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.placeofwork')),
            ],
            options={
                'verbose_name': 'course mentor',
                'verbose_name_plural': 'course mentors',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.coursementor'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.coursemodule'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.courseplan'),
        ),
    ]
