# Generated by Django 4.2 on 2024-09-27 17:43

import common.validatorsfile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.URLField(validators=[common.validatorsfile.facebook_validator]),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.URLField(verbose_name=[common.validatorsfile.instagram_validator]),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin',
            field=models.URLField(verbose_name=[common.validatorsfile.linkedin_validator]),
        ),
        migrations.AlterField(
            model_name='company',
            name='telegram',
            field=models.URLField(verbose_name=[common.validatorsfile.telegram_validator]),
        ),
    ]
