# Generated by Django 4.2 on 2024-09-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontactapplication',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='usercontactapplication',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='usercontactapplication',
            name='name_uz',
        ),
    ]
