# Generated by Django 4.2 on 2024-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='task',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
