# Generated by Django 4.2 on 2024-10-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_team_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
