# Generated by Django 4.2 on 2024-09-27 17:45

import common.validatorsfile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_company_facebook_alter_company_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.URLField(validators=[common.validatorsfile.instagram_validator]),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin',
            field=models.URLField(validators=[common.validatorsfile.linkedin_validator]),
        ),
        migrations.AlterField(
            model_name='company',
            name='telegram',
            field=models.URLField(validators=[common.validatorsfile.telegram_validator]),
        ),
    ]
