# Generated by Django 4.2 on 2024-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_computer_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
