# Generated by Django 4.2 on 2024-09-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_whyus_description_en_whyus_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourprogram',
            name='program_info',
        ),
        migrations.AddField(
            model_name='ourprograminfo',
            name='program',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.ourprogram'),
            preserve_default=False,
        ),
    ]
