# Generated by Django 4.2 on 2024-10-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontactapplication',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='usercontactapplication',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='usercontactapplication',
            name='name_uz',
        ),
    ]
