# Generated by Django 4.2 on 2024-09-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_ourprogram_program_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprograminfo',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_program_infos', to='common.ourprogram'),
        ),
    ]
