# Generated by Django 4.2 on 2024-09-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_ourprograminfo_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_mentor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_module',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_plan',
        ),
        migrations.AddField(
            model_name='coursementor',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseplan',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='common.course'),
            preserve_default=False,
        ),
    ]
