# Generated by Django 4.2 on 2024-09-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_course_course_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursementor',
            name='place_of_work',
        ),
        migrations.AddField(
            model_name='placeofwork',
            name='course_mentor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.coursementor'),
            preserve_default=False,
        ),
    ]
