# Generated by Django 4.2 on 2024-09-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_coursementor_place_of_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeofwork',
            name='course_mentor',
        ),
        migrations.AddField(
            model_name='placeofwork',
            name='course_mentor',
            field=models.ManyToManyField(to='common.coursementor'),
        ),
    ]
