# Generated by Django 4.2 on 2024-09-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_placeofwork_course_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeofwork',
            name='course_mentor',
            field=models.ManyToManyField(related_name='places', to='common.coursementor'),
        ),
    ]
