# Generated by Django 4.2 on 2024-09-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_placeofwork_course_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeofwork',
            name='course_mentor',
        ),
        migrations.AddField(
            model_name='placeofwork',
            name='course_mentor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='places', to='common.coursementor'),
            preserve_default=False,
        ),
    ]
