# Generated by Django 4.2 on 2024-09-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_placeofwork_course_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='lesson',
        ),
        migrations.AddField(
            model_name='modulelesson',
            name='course_module',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='common.coursemodule'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='coursementor',
            unique_together={('course', 'id')},
        ),
    ]
